DROP TABLE IF EXISTS `word_eng_dict` CASCADE;
DROP TABLE IF EXISTS `word_rus_dict` CASCADE;
DROP TABLE IF EXISTS `rus_eng` CASCADE;
DROP TABLE IF EXISTS `word_eng` CASCADE;
DROP TABLE IF EXISTS `word_rus` CASCADE;
DROP TABLE IF EXISTS `sound` CASCADE;
DROP TABLE IF EXISTS `dictionary` CASCADE;
