db:
  host: localhost
  user: root
  passwd: passwd
  db: voc-app-db-test
sound:
  eng:
  - path: third_party/eng_to_mp3/ultimate.json
    type: MULTI
  - path: third_party/eng_to_mp3/data.json
    type: SINGLE
cache:
  path: cache-unit-tests
ftp:
  host: 95.213.194.109
  user: voc-app-user
  passwd: voc-app-user-pass
  root-dir: files